demisto/demisto-py

- README.md
> Update md key usage

- demisto/client.py
Ability to use python server with username & password
We want to use python client in the **content test framework** (our flow based on username & password authentication)
- tested the examples scripts with api-key & also usage with username & password
> enable login with username & password

- README.md
also - no need to call login when using api key
> Add login example to readme

- README.md
- demisto/client.py
Adds into createIncident data when createInvestigation is set to true, else it omits the entry.
> Added createInvestigation field to CreateIncident

- incidents_search_example.py
Fixes: https://github.com/demisto/demisto-py/issues/13
> simple incidents search example

- .gitignore
- CHANGELOG.md
- README.md
- demisto_client/__init__.py
- demisto_client/demisto_api/api/default_api.py
- examples/create_incident_example.py
- requirements.txt
- test-requirements.txt
- tests/mocks_test.py
Fixes: https://github.com/demisto/demisto-py/issues/20
Fixes: https://github.com/demisto/etc/issues/19500
Also added dev env setup instructions
> Fix generic request + datetime parsing

- .gitignore
- README.md
- setup.py
add setup.py so it is possible to install from git. will create a tag once merged.
> Content build 1.x

- CHANGELOG.md
- README.md
- requirements.txt
- setup.py
Fix missing dependency (tzlocal) which was added as a requirement starting with 2.0.3 release.
> Fix missing dependency

- CHANGELOG.md
- demisto_client/demisto_api/api/default_api.py
- docs/DefaultApi.md
- docs/README.md
- server_api_swagger.json
* Added `investigation_add_entries_sync_handler` method creating a new entry in existing investigation.
* Fixed an issue in `integration_upload` method.
(ignore branch name - download file hasn't changed)
> integration_upload and investigation_add_entries_sync commands

- CHANGELOG.md
- demisto_client/__init__.py
Ready
Better error message when auth fails
> improved error message when missing auth parameters

- CHANGELOG.md
- demisto_client/demisto_api/api/default_api.py
Ready
The V2 API was not working correctly
> Changed v2 to v1 APi

- demisto_client/demisto_api/api/default_api.py
- docs/DefaultApi.md
- server_api_swagger.json
Ready
fixes: https://github.com/demisto/etc/issues/25785
The filter parm for the search-incidents should have been required.
> Changed filter param in search incidents to be required

- CHANGELOG.md
- demisto_client/demisto_api/rest.py
- gen-code.sh
Ready
fixes: https://github.com/demisto/etc/issues/28654
Modified the ApiException class to only return headers when the `DEMISTO_SENSITIVE_LOGGING` environment variable is set to true.
> Add env for sensitive logging

- demisto_client/demisto_api/rest.py
- gen-code.sh
- tests/mocks_test.py
Ready
Fix for broken import issue
> Fix for import issue

- CHANGELOG.md
- demisto_client/demisto_api/api_client.py
- gen-code.sh
Ready
https://github.com/demisto/etc/issues/30292
Add the ability to not cache the last response in the api_client to avoid memory leaks.
> Adding env variable that will allow us to not cache the last response

- CHANGELOG.md
- demisto_client/demisto_api/api/default_api.py
- docs/DefaultApi.md
- docs/README.md
- server_api_swagger.json
Ready
Add upload report api call
> add upload report api

- docs/DefaultApi.md
Ready
fixes: https://github.com/demisto/demisto-py/issues/66
> export_incidents_to_csv_batch fix example

- CHANGELOG.md
- requirements.txt
Ready
fixes: https://github.com/demisto/etc/issues/41194
> Fix test_create_incident

- CHANGELOG.md
- examples/update_automation_example.py
- tests/examples_test.py
Ready
fixes: https://github.com/demisto/etc/issues/41062
Uninitialized objects caused getting attributes from their properties to cause an error.
> update automation example fix

- demisto_client/demisto_api/api/default_api.py
- docs/DefaultApi.md
- server_api_swagger.json
Ready
related: https://github.com/demisto/etc/issues/42469
Added skip verify arg.
> Skip verify arg

- docs/DefaultApi.md
Ready
fixes: https://github.com/demisto/etc/issues/44678
Fixed "Search Investigations" docs
> Fix "Search Investigations" docs

- CHANGELOG.md
- demisto_client/demisto_api/api/default_api.py
- docs/DefaultApi.md
- server_api_swagger.json
Ready
related: https://github.com/demisto/etc/issues/45562
Add skipValidation param to upload packs command.
> Add skipValidation param to upload packs command

- CHANGELOG.md
- requirements.txt
Ready
TZLOCAL on older version fails on newer python
> feat: upgraded tzlocal to 4.1 and up

- CHANGELOG.md
> fix: changelog version

- requirements.txt
> fix: use tzlocal 4.* version

- CHANGELOG.md
- demisto_client/__init__.py
> update Authentication setting

- CHANGELOG.md
changelog for https://github.com/demisto/demisto-py/pull/86
> Update CHANGELOG.md for #86

- CHANGELOG.md
> 3.1.5 changelog

- CHANGELOG.md
- demisto_client/demisto_api/api_client.py
- gen-code.sh
- tests/mocks_test.py
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4113?filter=-1)
> Return partial errors

- CHANGELOG.md
- demisto_client/__init__.py
Ready
fixes: [link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-4908)
> fix xsiam configuration

- CHANGELOG.md
- demisto_client/demisto_api/rest.py
- gen-code.sh
Ready
Support proxy auth.
Didn't add any unit tests since I haven't found a good way to mock an authenticated proxy server.
Tested the code via mitmproxy on my local pc.
Was able to reproduce the issue.
> Support proxy auth

- CHANGELOG.md
- demisto_client/demisto_api/rest.py
- gen-code.sh
- tests/mocks_test.py
In Progress
related : https://jira-hq.paloaltonetworks.local/browse/XSUP-16632 
added url decoding of proxy credentials
> added url decoding of proxy credentials

- CHANGELOG.md
- demisto_client/demisto_api/api_client.py
- gen-code.sh
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8348
Added a check to determine whether the returned data is a string or bytes before writing to the file.
> Improve the way strings are handled when writing to files

- .circleci/config.yml
- CHANGELOG.md
- pyproject.toml
> Fix an issue with publish to pypi

- docs/DefaultApi.md
Ready
fixes: https://jira-hq.paloaltonetworks.local/browse/CIAC-8496
Updated the `export_incidents_to_csv_batch` docs.
> Fixed export incidents to CSV batch docs

- .circleci/config.yml
Ready
comment out the publish-to-test-pypi step until we automate version bumping
> [circleci] comment out the publish-to-test-pypi step

- CHANGELOG.md
- pyproject.toml
Ready
fixes: [link to the issue](https://jira-dc.paloaltonetworks.com/browse/CIAC-9602)
Bump package version to 3.12.14
> Bump version to v3.12.14

- .circleci/config.yml
> replaced deprecated ubuntu image

- demisto_client/__init__.py
fixes: https://jira-dc.paloaltonetworks.com/browse/XSUP-41641
We got Unauthorized error when tried to upload a layout due to not updated auth settings for XSOAR 8.
> XSUP-41641

- demisto_client/__init__.py
- demisto_client/demisto_api/api/default_api.py
fixes:
Added some functionalities to support testing playbooks use cases.
- [] Changelog entry
> added the possibility to send files as a request arg
